name: Publish CV as Github Page

on:
  push:
    branches: [ main ]

jobs:
  check_run:
    name: Check Commit Message
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"
  
  build:
    name: Build HTML Page
    runs-on: ubuntu-latest
    needs: check_run
    steps:
      - uses: actions/checkout@v2
      - uses: kelvintaywl/action-jsonresume-export@v1
        name: Export CV as HTML
        with:
          theme: onepage-plus
          resume_filepath: cv.json
          # modifies the index.html in-place
          output_filepath: index.html
      - name: Commit published HTML
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if [ -n "$(git status --porcelain index.html)" ]; then
            git add index.html
            git commit -m "[ci skip] chore(index.html): update cv page"
            echo ::set-output name=exit_code::0
          else
            echo ::set-output name=exit_code::1
          fi
      - name: Push changes
        uses: ad-m/github-push-action@master
        if: steps.commit.outputs.exit_code == 0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
